const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const scriptPath = path.join(__dirname, "lovart-prompt-translator.user.js");
const source = fs.readFileSync(scriptPath, "utf8");

assert.match(source, /@connect\s+translate\.volcengineapi\.com/, "missing Volcengine @connect host");
assert.match(source, /@version\s+0\.2\.11/, "version must be bumped for userscript updates");
assert.match(source, /@match\s+https:\/\/www\.runninghub\.cn\/\*/, "missing RunningHub @match host");
assert.match(source, /@match\s+https:\/\/www\.pinterest\.com\/\*/, "missing Pinterest @match host");
assert.match(source, /@noframes/, "script should not run inside iframes and create duplicate toolbars");
assert.match(source, /function shouldRunInCurrentWindow/, "missing top-window run gate");
assert.match(source, /window\.top\s*===\s*window\.self/, "run gate must only allow the top window");
assert.match(source, /function claimDocumentInstance/, "missing per-document singleton guard");
assert.match(source, /INSTANCE_MARKER_ID/, "missing singleton marker id");
assert.match(source, /document\.getElementById\(INSTANCE_MARKER_ID\)/, "singleton guard must detect an existing script instance");
assert.match(source, /document\.getElementById\(`\$\{SCRIPT_ID\}-toolbar`\)/, "singleton guard must detect an existing toolbar");
assert.match(source, /const AUTO_SHOW_TOOLBAR_HOSTS/, "missing host detection for auto toolbar display");
assert.match(source, /AUTO_SHOW_TOOLBAR_HOSTS\.has\(window\.location\.hostname\)/, "toolbar should detect supported hosts");
assert.match(source, /if \(shouldShowToolbarOnLoad\(\)\) \{\s*showToolbar\(\);\s*\}/, "supported hosts should show the toolbar on load");
assert.match(source, /provider:\s*"volcengine"/, "missing Volcengine provider option");
assert.match(source, /volcengineAccessKeyId/, "missing Volcengine Access Key config");
assert.match(source, /volcengineSecretAccessKey/, "missing Volcengine Secret Key config");
assert.match(source, /function signVolcengineRequest/, "missing Volcengine signing function");
assert.match(source, /function translateWithVolcengine/, "missing Volcengine translate function");
assert.match(source, /translate\.volcengineapi\.com\/\?Action=TranslateText&Version=2020-06-01/, "missing Volcengine TranslateText endpoint");
assert.match(source, /toolbarCollapsed:\s*false/, "missing toolbar collapsed state");
assert.match(source, /toolbarPosition:\s*null/, "missing toolbar position state");
assert.match(source, /data-action="toggle-collapse"/, "missing toolbar collapse button");
assert.match(source, /data-role="drag-handle"/, "missing toolbar drag handle");
assert.match(source, /function bindToolbarDrag/, "missing toolbar drag handler");
assert.match(source, /function applyToolbarState/, "missing toolbar state renderer");
assert.match(source, /function persistToolbarState/, "missing toolbar state persistence");
assert.match(source, /function toggleToolbarCollapsed/, "missing dedicated toolbar collapse toggler");
assert.match(source, /startedCollapsed/, "missing collapsed pointer state tracking");
assert.match(source, /toggleToolbarCollapsed\(false\)/, "collapsed click should expand on pointerup");
assert.match(source, /@connect\s+api\.siliconflow\.cn/, "missing SiliconFlow @connect host");
assert.match(source, /function isChatCompletionsEndpoint/, "missing chat completions endpoint detection");
assert.match(source, /function buildPromptTranslationMessages/, "missing chat completions messages builder");
assert.match(source, /messages:\s*buildPromptTranslationMessages/, "missing messages request body for chat completions");
assert.match(source, /function extractChatCompletionText/, "missing chat completions response parser");
assert.match(source, /choices\?\.\[0\]\?\.message\?\.content/, "missing choices message content extraction");
assert.match(source, /function replaceContentEditableText/, "missing robust contenteditable replacement");
assert.match(source, /const EDITABLE_SELECTOR/, "missing shared editable selector");
assert.match(source, /\[contenteditable\]:not\(\[contenteditable="false"\]\)/, "contenteditable plaintext-only must be supported");
assert.match(source, /function resolveFillTarget/, "missing nested fill target resolver");
assert.match(source, /function queryEditableDescendant/, "missing descendant editable lookup");
assert.match(source, /function resolveContentEditableTarget/, "missing real contenteditable target resolver");
assert.match(source, /function replaceContentEditableViaSelection/, "missing single-operation selection replacement");
assert.match(source, /function clearContentEditableText/, "missing explicit contenteditable clearing");
assert.match(source, /function insertContentEditableText/, "missing explicit contenteditable insertion");
assert.match(source, /function hardReplaceContentEditableText/, "missing hard replacement fallback");
assert.match(source, /function verifyFilledText/, "missing fill verification");
assert.match(source, /document\.execCommand\("delete", false\)/, "contenteditable fill must delete original first");
assert.match(source, /document\.execCommand\("selectAll", false\)/, "contenteditable clearing must use native select-all");
assert.match(source, /const fillTarget = resolveFillTarget\(element\)/, "fill must resolve real nested target before writing");
assert.match(source, /if \(isTextControl\(fillTarget\)\)/, "nested textarea/input should use value replacement path");
assert.match(source, /verifyClearedText\(element\)/, "missing clear verification before insert");
assert.match(source, /normalizeEditableText\(readEditableValue\(element\)\)/, "missing post-fill content check");
assert.match(source, /replaceChildren\(document\.createTextNode\(text\)\)/, "missing hard DOM replacement fallback");
assert.match(source, /function dispatchEditableEvents/, "missing centralized editable event dispatch");
assert.match(source, /includeData:\s*false/, "contenteditable fallback must not manually re-insert translated input data");
assert.doesNotMatch(source, /dispatchEditableEvents\(element,\s*text,\s*"insertText"\);/, "contenteditable path must not dispatch translated data as a second insertion");
assert.match(source, /let isFillingInput = false/, "missing fill re-entry guard");
assert.match(source, /if \(isFillingInput\) return;/, "fill action should ignore duplicate same-tick triggers");
assert.match(source, /let selectionTranslationToken = 0/, "missing stale selection translation guard");
assert.match(source, /function shouldAutoTranslateSelection/, "missing non-editable selection auto-translate gate");
assert.match(source, /function autoTranslateSelectionToChinese/, "missing auto Chinese translation helper");
assert.match(source, /translateText\(text,\s*"zh"\)/, "selected AI replies should translate directly to Chinese");
assert.match(source, /setBubblePreview\("翻译中\.\.\."\)/, "selection bubble should show translating hint");
assert.match(source, /if \(shouldAutoTranslateSelection\(selection\)\)/, "selection handler should trigger auto translation");

console.log("lovart-prompt-translator static checks passed");
